"""
Django settings for genebank_web project.

Generated by 'django-admin startproject' using Django 1.8.7.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os
import socket


def get_ip_address():
    s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    s.connect(("8.8.8.8", 80))
    ip = s.getsockname()[0]
    s.close()
    return ip

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

CACHE_DIR = os.path.abspath(os.path.join(BASE_DIR, 'cache'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'u2m7l-^qsh$)ny!1kr@d$w%rb681$v31jd4f*+2+g&q^1v*cfm'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
HOST_IP = get_ip_address()

if HOST_IP.startswith('192.168'):
    DEVELOPMENT_MACHINE = False
else:
    DEVELOPMENT_MACHINE = True

if DEVELOPMENT_MACHINE:
    DEBUG = True
    DATABASE = {'ENGINE': 'django.db.backends.sqlite3',
                'NAME': os.path.join(BASE_DIR, 'dev_default.sqlite3')}
    ALLOWED_HOSTS = ['*']
    PEDIGREE_DB = {'ENGINE': 'django.db.backends.sqlite3',
                   'NAME': os.path.join(BASE_DIR, 'dev_pedigree.sqlite3')}
    VAVILOV_APP_LOGGER = 'vavilov.debug'
else:
    DEBUG = False
    DATABASE = {'ENGINE': 'django.db.backends.sqlite3',
                'NAME': os.path.join(BASE_DIR, 'db.sqlite3')}
    PEDIGREE_DB = {'ENGINE': 'django.db.backends.sqlite3',
                   'NAME': os.path.join(BASE_DIR, 'pedigree.sqlite3')}
    VAVILOV_APP_LOGGER = 'vavilov.prod'
    ALLOWED_HOSTS = [HOST_IP]

DATABASES = {
    'default': DATABASE,
}
PEDIGREE_DATABASE = 'vavilov_pedigree'
DATABASES[PEDIGREE_DATABASE] = PEDIGREE_DB

DATABASE_ROUTERS = ['vavilov_pedigree.db_router.VavilovPedigreeRouter']
# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'vavilov.apps.VavilovAppConfig',
    'vavilov_pedigree.apps.VavilovPedigreeAppConfig',
    'django_tables2',
    'rest_framework',
    'rest_framework.authtoken',
    'guardian',
    'django_filters',
    'crispy_forms',
)
# AUTHENTICATION_BACKENDS = ('django.contrib.auth.backends.ModelBackend',
#                            'guardian.backends.ObjectPermissionBackend')
AUTHENTICATION_BACKENDS = (
    'guardian.backends.ObjectPermissionBackend',
    'django.contrib.auth.backends.ModelBackend',  # this is default
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'vavilov_web.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'vavilov.context_processors.googlemapkey'
            ],
        },
    },
]

WSGI_APPLICATION = 'vavilov_web.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'CET'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Genebank app settings
VAVILOV_PHENO_PHOTO_DIR = 'pheno_photos'
# GENEBANK_ACCESSION_FORM_FIELDS = ['accession', 'taxa', 'province']

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.TokenAuthentication'
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'vavilov.api.permissions.CustomObjectPermissions',
    )
}

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '%(levelname)s %(asctime)s %(module)s %(process)d %(thread)d %(message)s'
        },
        'simple': {
            'format': '%(levelname)s %(message)s'
        },
    },
    'filters': {
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
    },
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'filters': ['require_debug_true'],
            'class': 'logging.StreamHandler',
            'formatter': 'simple'
        },
        'mail_admins': {
            'level': 'ERROR',
            'class': 'django.utils.log.AdminEmailHandler',
        },
        'file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'vavilov.log'),
            'formatter': 'verbose',
        }
    },
    'loggers': {
        'vavilov.debug': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'filters': ['require_debug_true'],
        },
        'vavilov.prod': {
            'handlers': ['file'],
            'level': 'DEBUG'

        }
    }
}
