# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-06 09:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import vavilov.models
import vavilov.utils.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accession',
            fields=[
                ('accession_id', models.AutoField(primary_key=True, serialize=False)),
                ('accession_number', models.CharField(db_index=True, max_length=40, verbose_name='Accession number')),
            ],
            options={
                'permissions': (('view_accession', 'View Accession'),),
                'db_table': 'vavilov_accession',
            },
        ),
        migrations.CreateModel(
            name='AccessionProp',
            fields=[
                ('accession_prop_id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=255)),
                ('accession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vavilov.Accession')),
            ],
            options={
                'db_table': 'vavilov_accessionprop',
            },
        ),
        migrations.CreateModel(
            name='AccessionRelationship',
            fields=[
                ('accession_relationship_id', models.AutoField(primary_key=True, serialize=False)),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object', to='vavilov.Accession')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject', to='vavilov.Accession')),
            ],
            options={
                'permissions': (('view_accessionrelationship', 'View Accession Relationship'),),
                'db_table': 'vavilov_accession_relationship',
            },
        ),
        migrations.CreateModel(
            name='AccessionSynonym',
            fields=[
                ('accession_synonym_id', models.AutoField(primary_key=True, serialize=False)),
                ('synonym_code', models.CharField(max_length=255)),
                ('accession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vavilov.Accession')),
            ],
            options={
                'db_table': 'vavilov_accession_synonym',
            },
        ),
        migrations.CreateModel(
            name='AccessionTaxa',
            fields=[
                ('accession_organism_id', models.AutoField(primary_key=True, serialize=False)),
                ('creating_date', models.DateField(null=True)),
                ('accession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vavilov.Accession')),
            ],
            options={
                'permissions': (('view_accessiontaxa', 'View Accession Taxa'),),
                'db_table': 'vavilov_accession_organism',
            },
        ),
        migrations.CreateModel(
            name='Assay',
            fields=[
                ('assay_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('description', models.CharField(max_length=255, null=True)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('year', models.CharField(max_length=255, null=True)),
            ],
            options={
                'permissions': (('view_assay', 'View Assay'),),
                'db_table': 'vavilov_assay',
            },
        ),
        migrations.CreateModel(
            name='AssayPlant',
            fields=[
                ('assay_plant_id', models.AutoField(primary_key=True, serialize=False)),
                ('assay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vavilov.Assay')),
            ],
            options={
                'db_table': 'vavilov_assay_plant',
            },
        ),
        migrations.CreateModel(
            name='AssayProp',
            fields=[
                ('assay_prop_id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.TextField()),
                ('assay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vavilov.Assay')),
            ],
            options={
                'permissions': (('view_assayprop', 'View AssayProp'),),
                'db_table': 'vavilov_assayprop',
            },
        ),
        migrations.CreateModel(
            name='AssayTrait',
            fields=[
                ('assay_trait_id', models.AutoField(primary_key=True, serialize=False)),
                ('assay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vavilov.Assay')),
            ],
            options={
                'db_table': 'vavilov_assay_trait',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('country_id', models.AutoField(primary_key=True, serialize=False)),
                ('code2', models.CharField(db_index=True, max_length=2)),
                ('code3', models.CharField(db_index=True, max_length=3)),
                ('name', models.CharField(db_index=True, max_length=255)),
            ],
            options={
                'db_table': 'vavilov_country',
            },
        ),
        migrations.CreateModel(
            name='Cv',
            fields=[
                ('cv_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=48, unique=True)),
                ('description', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'vavilov_cv',
            },
        ),
        migrations.CreateModel(
            name='Cvterm',
            fields=[
                ('cvterm_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('definition', models.CharField(max_length=255, null=True)),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vavilov.Cv')),
            ],
            options={
                'db_table': 'vavilov_cvterm',
            },
        ),
        migrations.CreateModel(
            name='Db',
            fields=[
                ('db_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=48, unique=True)),
                ('description', models.CharField(max_length=255, null=True)),
                ('urlprefix', models.CharField(max_length=255, null=True)),
                ('url', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'vavilov_db',
            },
        ),
        migrations.CreateModel(
            name='Dbxref',
            fields=[
                ('dbxref_id', models.AutoField(primary_key=True, serialize=False)),
                ('accession_name', models.CharField(max_length=255)),
                ('db', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vavilov.Db')),
            ],
            options={
                'db_table': 'vavilov_dbxref',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('site', models.CharField(max_length=255, null=True)),
                ('province', models.CharField(max_length=255, null=True)),
                ('region', models.CharField(db_index=True, max_length=255, null=True)),
                ('latitude', models.DecimalField(decimal_places=4, max_digits=9, null=True)),
                ('longitude', models.DecimalField(decimal_places=4, max_digits=9, null=True)),
                ('altitude', models.IntegerField(null=True)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vavilov.Country')),
            ],
            options={
                'permissions': (('view_location', 'View Location'),),
                'db_table': 'vavilov_location',
            },
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('observation_id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.TextField(null=True)),
                ('creation_time', models.DateTimeField(null=True)),
                ('observer', models.CharField(max_length=255, null=True)),
                ('assay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vavilov.Assay')),
            ],
            options={
                'permissions': (('view_observation', 'View Observation'),),
                'db_table': 'vavilov_observation',
            },
        ),
        migrations.CreateModel(
            name='ObservationEntity',
            fields=[
                ('obs_entity_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vavilov.Cvterm')),
            ],
            options={
                'permissions': (('view_obs_entity', 'View Observation entity'),),
                'db_table': 'vavilov_observation_entity',
            },
        ),
        migrations.CreateModel(
            name='ObservationEntityPlant',
            fields=[
                ('plant_group_plant_id', models.AutoField(primary_key=True, serialize=False)),
                ('obs_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vavilov.ObservationEntity')),
            ],
            options={
                'db_table': 'vavilov_observation_entity_plant',
            },
        ),
        migrations.CreateModel(
            name='ObservationImages',
            fields=[
                ('observation_image_id', models.AutoField(primary_key=True, serialize=False)),
                ('observation_image_uid', models.CharField(max_length=255, unique=True)),
                ('image', models.ImageField(max_length=255, storage=vavilov.utils.storage.OnlyScanStorage(base_url='/media/', location='/home/peio/devel/pyenv3/vavilov_dev/vavilov_web/media'), upload_to=vavilov.models.get_photo_dir)),
                ('thumbnail', models.ImageField(blank=True, max_length=255, null=True, storage=vavilov.utils.storage.OnlyScanStorage(base_url='/media/', location='/home/peio/devel/pyenv3/vavilov_dev/vavilov_web/media'), upload_to=vavilov.models.get_thumb_dir)),
                ('observation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vavilov.Observation')),
            ],
            options={
                'permissions': (('view_observation_images', 'View observation images'),),
                'db_table': 'vavilov_observation_image',
            },
        ),
        migrations.CreateModel(
            name='ObservationRelationship',
            fields=[
                ('obs_relationship_id', models.AutoField(primary_key=True, serialize=False)),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object', to='vavilov.Observation')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject', to='vavilov.Observation')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vavilov.Cvterm')),
            ],
            options={
                'permissions': (('view_observationrelationship', 'View Observation Relationship'),),
                'db_table': 'vavilov_observation_relationship',
            },
        ),
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('passport_id', models.AutoField(primary_key=True, serialize=False)),
                ('local_name', models.CharField(db_index=True, max_length=255, null=True)),
                ('traditional_location', models.CharField(db_index=True, max_length=255, null=True)),
                ('acquisition_date', models.DateField(null=True)),
                ('collecting_date', models.DateField(null=True)),
                ('accession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vavilov.Accession')),
                ('biological_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='biological_status', to='vavilov.Cvterm', verbose_name='Biological status of accession')),
                ('collecting_source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collecting_source', to='vavilov.Cvterm', verbose_name='collecting_source')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vavilov.Location')),
            ],
            options={
                'permissions': (('view_passport', 'View Passport'),),
                'db_table': 'vavilov_passport',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('person_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=40, unique=True)),
                ('description', models.CharField(max_length=255, null=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vavilov.Cvterm')),
            ],
            options={
                'db_table': 'vavilov_person',
            },
        ),
        migrations.CreateModel(
            name='PersonRelationship',
            fields=[
                ('person_relationship_id', models.AutoField(primary_key=True, serialize=False)),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object', to='vavilov.Person')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject', to='vavilov.Person')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vavilov.Cvterm')),
            ],
            options={
                'db_table': 'vavilov_contact_relationship',
            },
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('plant_id', models.AutoField(primary_key=True, serialize=False)),
                ('plant_name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('experimental_field', models.CharField(max_length=255, null=True)),
                ('row', models.CharField(max_length=10, null=True)),
                ('column', models.CharField(max_length=10, null=True)),
                ('pot_number', models.CharField(max_length=10, null=True)),
                ('accession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vavilov.Accession')),
            ],
            options={
                'permissions': (('view_plant', 'View Plant'),),
                'db_table': 'vavilov_plant',
            },
        ),
        migrations.CreateModel(
            name='Pub',
            fields=[
                ('pub_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'vavilov_pub',
            },
        ),
        migrations.CreateModel(
            name='Taxa',
            fields=[
                ('taxa_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('rank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vavilov.Cvterm')),
            ],
            options={
                'db_table': 'vavilov_taxa',
            },
        ),
        migrations.CreateModel(
            name='TaxaRelationship',
            fields=[
                ('taxa_relationship_id', models.AutoField(primary_key=True, serialize=False)),
                ('taxa_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taxa_object', to='vavilov.Taxa')),
                ('taxa_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taxa_subject', to='vavilov.Taxa')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vavilov.Cvterm')),
            ],
            options={
                'db_table': 'vavilov_taxa_relationship',
            },
        ),
        migrations.CreateModel(
            name='Trait',
            fields=[
                ('trait_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vavilov.Cvterm')),
            ],
            options={
                'permissions': (('view_trait', 'View Trait'),),
                'db_table': 'vavilov_trait',
            },
        ),
        migrations.CreateModel(
            name='TraitProp',
            fields=[
                ('trait_prop_id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=255)),
                ('trait', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vavilov.Trait')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vavilov.Cvterm')),
            ],
            options={
                'db_table': 'vavilov_trait_prop',
            },
        ),
        migrations.AddField(
            model_name='observationentityplant',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vavilov.Plant'),
        ),
        migrations.AddField(
            model_name='observation',
            name='obs_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vavilov.ObservationEntity'),
        ),
        migrations.AddField(
            model_name='observation',
            name='trait',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vavilov.Trait'),
        ),
        migrations.AddField(
            model_name='cvterm',
            name='dbxref',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vavilov.Dbxref'),
        ),
        migrations.AddField(
            model_name='assaytrait',
            name='trait',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vavilov.Trait'),
        ),
        migrations.AddField(
            model_name='assayprop',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vavilov.Cvterm'),
        ),
        migrations.AddField(
            model_name='assayplant',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vavilov.Plant'),
        ),
        migrations.AddField(
            model_name='assay',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vavilov.Location'),
        ),
        migrations.AddField(
            model_name='assay',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accessiontaxa',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vavilov.Person'),
        ),
        migrations.AddField(
            model_name='accessiontaxa',
            name='pub',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vavilov.Pub'),
        ),
        migrations.AddField(
            model_name='accessiontaxa',
            name='taxa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vavilov.Taxa'),
        ),
        migrations.AddField(
            model_name='accessionsynonym',
            name='synonym_institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vavilov.Person'),
        ),
        migrations.AddField(
            model_name='accessionsynonym',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vavilov.Cvterm'),
        ),
        migrations.AddField(
            model_name='accessionrelationship',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vavilov.Cvterm'),
        ),
        migrations.AddField(
            model_name='accessionprop',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vavilov.Cvterm'),
        ),
        migrations.AddField(
            model_name='accession',
            name='dbxref',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vavilov.Dbxref'),
        ),
        migrations.AddField(
            model_name='accession',
            name='institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vavilov.Person', verbose_name='Institute_code'),
        ),
        migrations.AddField(
            model_name='accession',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vavilov.Cvterm'),
        ),
        migrations.AlterUniqueTogether(
            name='traitprop',
            unique_together=set([('trait', 'type')]),
        ),
        migrations.AlterUniqueTogether(
            name='taxarelationship',
            unique_together=set([('taxa_subject', 'taxa_object', 'type')]),
        ),
        migrations.AlterUniqueTogether(
            name='dbxref',
            unique_together=set([('db', 'accession_name')]),
        ),
        migrations.AlterUniqueTogether(
            name='cvterm',
            unique_together=set([('cv', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='assaytrait',
            unique_together=set([('trait', 'assay')]),
        ),
        migrations.AlterUniqueTogether(
            name='assayprop',
            unique_together=set([('assay', 'type')]),
        ),
        migrations.AlterUniqueTogether(
            name='assayplant',
            unique_together=set([('assay', 'plant')]),
        ),
        migrations.AlterUniqueTogether(
            name='accessiontaxa',
            unique_together=set([('accession', 'taxa', 'creating_date')]),
        ),
    ]
