# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-10 13:48
from __future__ import unicode_literals

from django.db import migrations, models
import vavilov.models
import vavilov.utils.storage


class Migration(migrations.Migration):

    dependencies = [
        ('vavilov', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observationimages',
            name='image',
            field=models.ImageField(max_length=255, storage=vavilov.utils.storage.OnlyScanStorage(base_url='/media/', location='/home/jope/devel/vavilov_dev/vavilov_web/media'), upload_to=vavilov.models.get_photo_dir),
        ),
        migrations.AlterField(
            model_name='observationimages',
            name='thumbnail',
            field=models.ImageField(blank=True, max_length=255, null=True, storage=vavilov.utils.storage.OnlyScanStorage(base_url='/media/', location='/home/jope/devel/vavilov_dev/vavilov_web/media'), upload_to=vavilov.models.get_thumb_dir),
        ),
        migrations.AlterField(
            model_name='traitprop',
            name='value',
            field=models.TextField(max_length=255),
        ),
    ]
