# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-05 10:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accession',
            fields=[
                ('accession_id', models.AutoField(primary_key=True, serialize=False)),
                ('accession_number', models.CharField(max_length=255)),
                ('collecting_number', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'vavilov_pedigree_accession',
            },
        ),
        migrations.CreateModel(
            name='Assay',
            fields=[
                ('assay_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'vavilov_pedigree_assay',
            },
        ),
        migrations.CreateModel(
            name='CrossExperiment',
            fields=[
                ('cross_experiment_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255, unique=True)),
                ('assay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vavilov_pedigree.Assay')),
            ],
            options={
                'db_table': 'vavilov_pedigree_cross_experiment',
            },
        ),
        migrations.CreateModel(
            name='CrossExperimentSeedLot',
            fields=[
                ('cross_experiment_seed_lot_id', models.AutoField(primary_key=True, serialize=False)),
                ('cross_experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vavilov_pedigree.CrossExperiment')),
            ],
            options={
                'db_table': 'vavilov_pedigree_cross_experiment_seed_lot',
            },
        ),
        migrations.CreateModel(
            name='CrossPlant',
            fields=[
                ('cross_plant_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=10)),
                ('cross', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vavilov_pedigree.CrossExperiment')),
            ],
            options={
                'db_table': 'vavilov_pedigree_cross_plant',
            },
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('plant_id', models.AutoField(primary_key=True, serialize=False)),
                ('plant_name', models.CharField(max_length=255, unique=True)),
                ('experimental_field', models.CharField(max_length=255, null=True)),
                ('row', models.CharField(max_length=10, null=True)),
                ('column', models.CharField(max_length=10, null=True)),
                ('pot_number', models.CharField(max_length=10, null=True)),
            ],
            options={
                'db_table': 'vavilov_pedigree_plant',
            },
        ),
        migrations.CreateModel(
            name='PlantRelationship',
            fields=[
                ('plant_relationship_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(default='is_clone', max_length=100)),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object', to='vavilov_pedigree.Plant')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject', to='vavilov_pedigree.Plant')),
            ],
            options={
                'db_table': 'vavilov_pedigree_plant_relationshp',
            },
        ),
        migrations.CreateModel(
            name='SeedLot',
            fields=[
                ('seed_lot_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.CharField(max_length=255, null=True)),
                ('seeds_weight', models.FloatField(null=True)),
                ('fruit', models.CharField(max_length=10, null=True)),
                ('location', models.CharField(max_length=100, null=True)),
                ('accession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vavilov_pedigree.Accession')),
            ],
            options={
                'db_table': 'vavilov_pedigree_seed_lot',
            },
        ),
        migrations.AddField(
            model_name='plant',
            name='seed_lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vavilov_pedigree.SeedLot'),
        ),
        migrations.AddField(
            model_name='crossplant',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vavilov_pedigree.Plant'),
        ),
        migrations.AddField(
            model_name='crossexperimentseedlot',
            name='seed_lot',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='vavilov_pedigree.SeedLot'),
        ),
    ]
